### ISSUE TITLE
fractional_digits option not respected with 2.x?

### ISSUE THREAD

**Issue by robotvert** [kipcole9/cldr_numbers#7]
Hi,

When formatting a float I'm getting a strange output:

```elixir
Decimal.new("1.40")  # https://github.com/ericmj/decimal
# => #Decimal<1.40>

value = Decimal.to_float(Decimal.new("1.40"))
# => 1.4

i
# => Term
# =>   1.4
# => Data type
# =>   Float
# => Reference modules
# =>   Float
# => Implemented protocols
# =>   Apex.Format, Inspect, Phoenix.Param, Jason.Encoder, IEx.Info, DeepMerge.Resolver, String.Chars, List.Chars, Plug.Exception

Decapx.Cldr.Number.to_string(value, fractional_digits: 2)
# => {:ok, "1,400 000 000 000 000 1"}
```

See [that unrelated issue](https://github.com/kipcole9/cldr/issues/93) I opened a few weeks ago for info about my app's setup.

If memory serves, when using 1.x I had expected results.
Maybe I was relying on a odd behavior all along and 2.x fixed it?

Any advice welcome!

**Comment by kipcole9** [comment]
Sorry for the inconvenience.  The bug was actually in [cldr_utils](https://github.com/kipcole9/cldr_utils).  I have reverted to the hand-rolled rounding code from previous releases and pushed [version 2.0.5 on hex](https://hex.pm/packages/cldr_utils/2.0.5).

Floats are such horrible thing :-)

I have added some more test cases so i hope that this issue is resolved to your satisfaction.

**Comment by robotvert** [comment]
Fixed! Thanks for the swift action as usual!
